Feat add object view 8
Swift-Coding-Club/throw_away pull request #11
Opened 2022-11-01 13:27 UTC by 2dubu

## 🙋🏻‍♀️ 리뷰어님께 🙋🏻
비움 프로젝트 첫 PR이다보니 컨벤션이 맞지 않는 부분이 있을 수도 있을 것 같아요. 틀린 부분이 있으면 편하게 알려주세요. :)
주말 회의에 자주 참여하지 못하다보니 평일에 열심히 해봤습니당

## 📚 작업 사항
- 물건 이미지 입력 칸 UI 구현
- 물건 이미지 추가 기능 구현
- 물건 이름 / 물건 설명 입력 칸 UI 구현
- 날짜 선택 칸 UI 구현

## 🚀 실행
<img width="300" alt="스크린샷 2022-11-01 오전 2 57 45" src="https://user-images.githubusercontent.com/70322775/199242416-af9ceb8f-f486-4904-9ac3-21e650822506.png">

## 🌤 고민과 해결
1. DatePicker 디자인을 커스텀 하는 것이 생각보다 까다로워 날짜 선택 부분의 UI가 피그마와 조금 다릅니다. 커스텀에 자신있으신 분이 있으시면 수정 부탁드립니다!

2. 최소 타겟을 iOS 15.0으로 수정했습니다. iOS 15.0부터 사용할 수 있는 @FocusState와 Keboard toolBar를 사용해보는건 어떨까요? (필수는 아니지만 추후에 업데이트 해봐도 좋을 것 같습니다.)

3. 아직 모델의 형태나 앱의 메인 틀이 잡혀져 있지 않아 입력한 데이터를 CoreData에 저장하는 코드는 없으며, Navigation쪽 UI 코드도 아직은 구현되어 있지 않습니다.

2022-11-01 13:30 UTC, 2dubu commented
### 폴더 구조도 잡혀있지 않아서 일단 폴더 하나 생성해서 진행했어요!

2022-11-01 14:17 UTC, Jinsujin approved these changes
와우 엄청 빠르게 작업하셨네요! 👍 SwiftUI 햇병아리로써 넘나 대단....😳
얼른 모델작업 해드려야 만들어주신 UI 와 붙일수 있겠어요! 고생하셨습니다!

2022-11-01 14:17 UTC, Jinsujin commented on ThrowAway/ThrowAway/AddObject/AddObjectView.swift
> +                .overlay(Rectangle().stroke(borderColor, lineWidth: 1))
🟢 SwiftUI 는 DatePicker 를 사용하기도 편하네요! 코드를 읽는 입장에서도 가독성이 좋다고 느껴졌습니다!

2022-11-01 14:17 UTC, Jinsujin commented on ThrowAway/ThrowAway/AddObject/PhotoPicker.swift
> +struct PhotoPicker: UIViewControllerRepresentable {
🟢 SwiftUI 에서 UIViewController 를 사용하려면 이렇게 사용하는군요...

2022-11-01 14:17 UTC, Jinsujin commented on ThrowAway/ThrowAway/AddObject/PhotoPicker.swift
> +class Coordinator: PHPickerViewControllerDelegate {
🟡 질문) Coordinator 패턴이 떠오르는 네이밍인데, 다른 객체에서도 사용할 수 있는 공용 클래스인걸까요? PHPicker 를 사용안해보았지만, 코드상으로는 선택한 아이템을 부모에게 넘겨주는듯 한데, 어떤 의미로 Coordinator 라는 네이밍을 선택하셨는지 궁금합니다!

2022-11-01 14:22 UTC, Jinsujin commented
1. DatePicker 디자인을 커스텀 하는 것이 생각보다 까다로워 날짜 선택 부분의 UI가 피그마와 조금 다릅니다. 커스텀에 자신있으신 분이 있으시면 수정 부탁드립니다! 
=> 지금 UI 도 좋은것 같습니다! 미리보기 이미지 넣어주셔서 실행을 안해도 확인할 수 있어서 좋았어요 감사합니다! 😊

2. 최소 타겟을 iOS 15.0으로 수정했습니다. iOS 15.0부터 사용할 수 있는 https://github.com/focusstate와 Keboard toolBar를 사용해보는건 어떨까요? (필수는 아니지만 추후에 업데이트 해봐도 좋을 것 같습니다.)
=> 좋습니다! 도전할거리는 언제든 환영이예요
링크 걸어주신 https://github.com/focusstate 이곳은 올라온 저장소가 없어 확인이 안되네요 🥲

2022-11-01 14:48 UTC, 2dubu commented on ThrowAway/ThrowAway/AddObject/PhotoPicker.swift
> +class Coordinator: PHPickerViewControllerDelegate {
Coordinator 클래스 이름을 다른 것으로 써본 적이 없네요.. 보통 다 이렇게 사용해서요! ㅎㅎ
SwiftUI에서 UIKit코드를 사용하면서 Delegate를 구현할 때 필요한 녀석입니다.

https://ally10.tistory.com/44 요 글을 참고해봐도 좋을 것 같아요

2022-11-01 14:52 UTC, 2dubu commented
@Jinsujin 말씀해주신 깃허브 링크는 오타인 것 같아요.
@.FocusState(. 빼고)와 Keboard toolBar라고 입력했는데 @ 때문에 링크로 인식했나봐요 😂

2022-11-02 03:47 UTC, oddukgi commented on ThrowAway/ThrowAway/AddObject/PhotoPicker.swift
> +}
🟢  `if itemProvider.canLoadObject(ofClass: UIImage.self) { }` 이 블록을 분리 했으면 좋겠네요.
```swift 
    if !itemProvider.canLoadObject(ofClass: UIImage.self) { 
         return 
    }    
```

2022-11-02 03:48 UTC, oddukgi approved these changes

2022-11-02 03:49 UTC, oddukgi approved these changes

2022-11-02 03:52 UTC, oddukgi requested changes
전체적으로 다 좋구요. 피드백 남긴 부분중에 반영할 부분이 있다면 업데이트 해주세요.

2022-11-02 03:52 UTC, oddukgi approved these changes

2022-11-02 08:23 UTC, merged