[Feature] 리스트 화면 비움, 삭제 처리 #24
Swift-Coding-Club/throw_away pull request #25
Opened 2022-11-22 13:12 UTC by oddukgi

### 📚 작업 사항
1. 상품 비움처리
    **a. 리스트에서 셀 스와이핑을 → (왼쪽에서 오른쪽으로)**
        - 리스트 상단 `비움` 버튼을 누르면, 셀을 다중 선택하여 비움처리
    **b. 비움할때 경고창 띄우기**
        - 셀스와이핑: `립스틱을 비움처리 하시겠습니까?` 
     **c. 다중선택: `선택한 3개 물건을 비움처리 하시겠습니까?`**
2.  리스트에서 상품 셀 삭제
     **리스트화면에서, 셀 스와이핑을 ← (오른쪽에서 왼쪽으로)**

### 🌤 작업 이미지

<img src="https://user-images.githubusercontent.com/3068049/203321223-f5143f55-1aa3-403f-a09a-5cc2be52f1f5.png" width="250"> <img src="https://user-images.githubusercontent.com/3068049/203321623-dee26898-546c-4484-9b99-fe202e41569b.png" width="250"> <img src="https://user-images.githubusercontent.com/3068049/203321801-72d9e4fd-1ee9-40a7-b500-71efe1d30716.png" width ="250">
<img src="https://user-images.githubusercontent.com/3068049/203322135-544fc0d2-0eb2-4a18-8f92-09cf4c38d0e0.png" width = "230">  <img src="https://user-images.githubusercontent.com/3068049/203322212-d2497797-4952-43d1-8d56-e3e476599004.png" width = "230"> <img src="https://user-images.githubusercontent.com/3068049/203322392-a2388525-ccee-4dd1-99d5-ca26af254b8a.png" width = "230">

2022-11-23 05:49 UTC, JUNY0110 requested changes
브랜치가 Main으로 지정되어있습니다. Develop으로 변경해주시면 감사하겠습니다~

2022-11-24 17:37 UTC, Jinsujin approved these changes
삭제, 비움 모두 처리 하셨군요! 
이미지 첨부해주셔서 확인이 더 편했습니다 감사합니다 😊
develop 브랜치로 바꿔주셔서 어프룹합니다!

2022-11-24 17:37 UTC, Jinsujin commented on ThrowAway/ThrowAway/View Controllers/ProductListViewController.swift
> +        didSet {
🟢 오우 didSet 으로 바꾸셨군요..! 저랑 같은 생각을 하신것 같아요!

2022-11-26 04:42 UTC, JUNY0110 approved these changes

2022-11-26 04:42 UTC, merged